export type Region = "Americas" | "Europe" | "Asia Pacific" | "Middle East" | "Africa";

export type DataCenter = {
  id: string;
  rank: number;
  name: string;
  operator: string;
  city: string;
  country: string;
  countryCode: string;
  flag: string;
  region: Region;
  lat: number;
  lng: number;
  status: "Operational" | "Building" | "Announced";
  capacityMw: number;
  capacityLabel: string;
  capacityBasis: "Operational" | "Planned" | "Campus envelope" | "Phase one";
  capacityDetail: string;
  detail: string;
  source: string;
};

const US_RANKING = "https://usdatamap.com/rankings/biggest-hyperscale-data-centers";
const KNIGHT_FRANK = "https://www.knightfrank.co.uk/content-assets/211eb9c4e9e44027a77942ade93d66b0/datacentrescq2026.pdf";
const OPENAI_STARGATE = "https://openai.com/index/stargate-community/";
const META_INFRA = "https://about.fb.com/news/2026/04/infrastructure-explained-meta-data-centers/";

export const DATA_CENTERS: DataCenter[] = [
  { id:"hyperion", rank:1, name:"Hyperion", operator:"Meta", city:"Richland Parish, Louisiana", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:32.44, lng:-91.76, status:"Building", capacityMw:5000, capacityLabel:"5 GW full buildout", capacityBasis:"Campus envelope", capacityDetail:"Initial development is reported at roughly 2 GW, with the Louisiana campus designed to scale toward 5 GW.", detail:"Meta's largest AI training campus, built around dense accelerator clusters and multi-year energy infrastructure expansion.", source:"https://about.fb.com/news/2025/12/metas-richland-parish-data-center-supports-louisiana-economy-875-million-in-contracts/" },
  { id:"stargate-uae", rank:2, name:"Stargate UAE Campus", operator:"G42 · OpenAI · Oracle", city:"Abu Dhabi", country:"United Arab Emirates", countryCode:"AE", flag:"🇦🇪", region:"Middle East", lat:24.45, lng:54.38, status:"Building", capacityMw:5000, capacityLabel:"5 GW campus envelope", capacityBasis:"Campus envelope", capacityDetail:"The first Stargate cluster is planned at 1 GW, with 200 MW targeted for the opening phase inside the wider 5 GW campus.", detail:"The first international Stargate deployment and one of the largest announced concentrations of sovereign AI compute.", source:"https://openai.com/index/introducing-stargate-uae/" },
  { id:"rainier", rank:3, name:"Project Rainier", operator:"AWS · Anthropic", city:"New Carlisle, Indiana", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:41.70, lng:-86.51, status:"Operational", capacityMw:2200, capacityLabel:"2.2 GW campus envelope", capacityBasis:"Campus envelope", capacityDetail:"Power figure covers the wider New Carlisle development; the live AI cluster uses nearly 500,000 Trainium2 chips and continues to expand.", detail:"AWS's purpose-built distributed AI supercomputer for training and serving Anthropic models.", source:"https://www.aboutamazon.com/news/aws/aws-project-rainier-ai-trainium-chips-compute-cluster" },
  { id:"stargate-jupiter", rank:4, name:"Project Jupiter", operator:"OpenAI · Oracle", city:"Doña Ana County, New Mexico", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:31.80, lng:-106.64, status:"Building", capacityMw:2200, capacityLabel:"2.2 GW planned", capacityBasis:"Planned", capacityDetail:"Full campus plan reported across multiple phases; live capacity will ramp building by building.", detail:"A large Stargate expansion designed for frontier-model training near the Texas–New Mexico border.", source:OPENAI_STARGATE },
  { id:"microsoft-pecos", rank:5, name:"Pecos AI Campus", operator:"Microsoft", city:"Pecos, Texas", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:31.42, lng:-103.49, status:"Announced", capacityMw:2000, capacityLabel:"2 GW planned", capacityBasis:"Planned", capacityDetail:"Long-range campus target from public development tracking; commissioning is expected in phases.", detail:"A proposed Microsoft AI factory campus sized for gigawatt-class accelerator infrastructure.", source:US_RANKING },
  { id:"colossus-southaven", rank:6, name:"Colossus 2 Southaven", operator:"xAI", city:"Southaven, Mississippi", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:34.99, lng:-90.01, status:"Building", capacityMw:2000, capacityLabel:"2 GW target", capacityBasis:"Planned", capacityDetail:"Target capacity for the Mississippi expansion; energized load is expected to ramp through several phases.", detail:"xAI's next-scale cluster planned as an extension of the Memphis compute footprint.", source:"https://x.ai/memphis/info" },
  { id:"tract-reno", rank:7, name:"Tract Reno Campus", operator:"Tract", city:"Reno, Nevada", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:39.55, lng:-119.83, status:"Announced", capacityMw:1500, capacityLabel:"1.5 GW planned", capacityBasis:"Campus envelope", capacityDetail:"Master-planned, AI-ready campus capacity rather than currently energized IT load.", detail:"A very large AI-ready hyperscale development designed for multiple high-density tenants.", source:US_RANKING },
  { id:"vantage-tx12", rank:8, name:"TX12 Frontier Campus", operator:"Vantage Data Centers", city:"Abilene, Texas", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:32.46, lng:-99.76, status:"Building", capacityMw:1400, capacityLabel:"1.4 GW planned", capacityBasis:"Campus envelope", capacityDetail:"Full campus utility plan; individual buildings will enter service in stages.", detail:"A high-density frontier campus in the expanding Abilene AI infrastructure corridor.", source:US_RANKING },
  { id:"abilene", rank:9, name:"Stargate Abilene", operator:"OpenAI · Oracle · Crusoe", city:"Abilene, Texas", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:32.45, lng:-99.73, status:"Operational", capacityMw:1200, capacityLabel:"1.2 GW full campus", capacityBasis:"Campus envelope", capacityDetail:"Roughly 200 MW was energized in the first phase; the eight-building campus is designed for about 1.2 GW.", detail:"The flagship Stargate campus, already training and serving frontier AI systems while later buildings come online.", source:"https://openai.com/index/five-new-stargate-sites/" },
  { id:"colossus-2", rank:10, name:"Colossus 2 Memphis", operator:"xAI", city:"Memphis, Tennessee", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:35.15, lng:-90.06, status:"Building", capacityMw:1200, capacityLabel:"1.2 GW tracked", capacityBasis:"Planned", capacityDetail:"Public project tracking figure for the expanded Memphis footprint; capacity is being energized incrementally.", detail:"The second-generation xAI supercluster, expanding the original Colossus site with denser AI compute.", source:"https://x.ai/memphis/info" },
  { id:"spark-saudi", rank:11, name:"SPARK AI Campus", operator:"DataVolt · HUMAIN", city:"King Salman Energy Park", country:"Saudi Arabia", countryCode:"SA", flag:"🇸🇦", region:"Middle East", lat:25.98, lng:49.62, status:"Building", capacityMw:1200, capacityLabel:"1.2 GW scalable", capacityBasis:"Campus envelope", capacityDetail:"The first disclosed phase is approximately 300 MW, with the wider campus planned to scale toward 1.2 GW.", detail:"A renewable-led AI infrastructure campus positioned to attract sovereign and global model workloads.", source:"https://data-volt.com/media/breaking-news/humain-and-datavolt-join-forces-to-attract-large-scale-ai-workloads-to-saudi-arabia/" },
  { id:"vizag", rank:12, name:"Visakhapatnam AI Hub", operator:"Google · AdaniConneX", city:"Visakhapatnam, Andhra Pradesh", country:"India", countryCode:"IN", flag:"🇮🇳", region:"Asia Pacific", lat:17.69, lng:83.22, status:"Building", capacityMw:1000, capacityLabel:"Gigawatt-scale", capacityBasis:"Planned", capacityDetail:"Google describes the hub as gigawatt-scale; buildout is planned across several campuses from 2026 onward.", detail:"Google's first purpose-built AI hub in India, paired with clean energy and new subsea connectivity.", source:"https://blog.google/intl/en-in/company-news/our-first-ai-hub-in-india-powered-by-a-15-billion-investment/" },
  { id:"jamnagar", rank:13, name:"Jamnagar AI Campus", operator:"Reliance Industries", city:"Jamnagar, Gujarat", country:"India", countryCode:"IN", flag:"🇮🇳", region:"Asia Pacific", lat:22.47, lng:70.07, status:"Building", capacityMw:1000, capacityLabel:"1 GW target", capacityBasis:"Planned", capacityDetail:"Full-build target tied to Reliance's energy and digital infrastructure ecosystem.", detail:"A sovereign AI compute campus planned alongside Reliance's large renewable-energy complex.", source:"https://www.ril.com/ar2024-25/pdf/reliance-ir-2025.pdf" },
  { id:"prometheus", rank:14, name:"Prometheus", operator:"Meta", city:"New Albany, Ohio", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:40.08, lng:-82.81, status:"Building", capacityMw:1000, capacityLabel:"1 GW class", capacityBasis:"Planned", capacityDetail:"Reported target for Meta's next major AI training cluster; construction and energization remain phased.", detail:"Meta's Ohio AI supercluster intended to complement the larger Hyperion campus.", source:META_INFRA },
  { id:"aws-salem", rank:15, name:"AWS Salem AI Campus", operator:"AWS", city:"Salem Township, Pennsylvania", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:41.09, lng:-76.15, status:"Building", capacityMw:1000, capacityLabel:"1 GW planned", capacityBasis:"Campus envelope", capacityDetail:"Publicly tracked campus envelope for AI and cloud infrastructure; not all capacity is contracted or live.", detail:"A major Pennsylvania expansion intended for high-density AI and cloud workloads.", source:US_RANKING },
  { id:"prime-quincy", rank:16, name:"Prime Quincy AI Campus", operator:"Prime Data Centers", city:"Quincy, Washington", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:47.23, lng:-119.85, status:"Building", capacityMw:1000, capacityLabel:"1 GW planned", capacityBasis:"Campus envelope", capacityDetail:"Master-plan capacity across multiple data halls, with power delivered in stages.", detail:"An AI-ready hyperscale campus benefiting from the region's large hydroelectric power base.", source:US_RANKING },
  { id:"compass-meridian", rank:17, name:"Meridian AI Campus", operator:"Compass Datacenters", city:"Meridian, Mississippi", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:32.37, lng:-88.69, status:"Building", capacityMw:1000, capacityLabel:"1 GW planned", capacityBasis:"Campus envelope", capacityDetail:"Full site plan for multiple high-density buildings; current energized capacity is lower.", detail:"A gigawatt-scale hyperscale development designed around next-generation AI tenants.", source:US_RANKING },
  { id:"tract-storey", rank:18, name:"Storey County AI Campus", operator:"Tract", city:"Sparks, Nevada", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:39.54, lng:-119.75, status:"Announced", capacityMw:1000, capacityLabel:"1 GW planned", capacityBasis:"Campus envelope", capacityDetail:"Master-planned AI-ready power capacity, subject to phased utility and tenant delivery.", detail:"A large hyperscale campus in Nevada's established data-center corridor.", source:US_RANKING },
  { id:"aragon", rank:19, name:"Aragón AI Region", operator:"Microsoft", city:"Zaragoza, Aragón", country:"Spain", countryCode:"ES", flag:"🇪🇸", region:"Europe", lat:41.65, lng:-0.89, status:"Building", capacityMw:900, capacityLabel:"~900 MW regional plan", capacityBasis:"Campus envelope", capacityDetail:"Combined planning envelope across Microsoft's Aragón data-center locations rather than one live building.", detail:"A major European cloud and AI region built around renewable power and new grid capacity.", source:"https://news.microsoft.com/europe/2024/06/14/microsoft-to-invest-6-69-billion-in-developing-new-data-centres-in-aragon-spain/" },
  { id:"tract-buckeye", rank:20, name:"Buckeye AI Campus", operator:"Tract", city:"Buckeye, Arizona", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:33.44, lng:-112.59, status:"Announced", capacityMw:800, capacityLabel:"800 MW planned", capacityBasis:"Campus envelope", capacityDetail:"Full AI-ready campus plan; capacity will depend on utility delivery and tenant phases.", detail:"A desert hyperscale development designed for dense AI infrastructure and large cloud tenants.", source:US_RANKING },
  { id:"lordstown", rank:21, name:"Stargate Lordstown", operator:"OpenAI · SoftBank", city:"Lordstown, Ohio", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:41.17, lng:-80.86, status:"Building", capacityMw:767, capacityLabel:"767 MW planned", capacityBasis:"Planned", capacityDetail:"Reported full-build capacity from development-market tracking; the first phase will be smaller.", detail:"A Midwest Stargate campus being developed with SoftBank for large-scale frontier AI workloads.", source:"https://openai.com/index/five-new-stargate-sites/" },
  { id:"stargate-michigan", rank:22, name:"Stargate Michigan", operator:"OpenAI · Oracle · Related Digital", city:"Saline Township, Michigan", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:42.17, lng:-83.78, status:"Building", capacityMw:700, capacityLabel:"~700 MW planned", capacityBasis:"Planned", capacityDetail:"Approximate campus envelope from public planning and power disclosures; not current operating load.", detail:"A battery-supported Stargate campus designed to add major AI capacity in the Great Lakes region.", source:OPENAI_STARGATE },
  { id:"s7-sydney", rank:23, name:"S7 Sydney AI Campus", operator:"NEXTDC · OpenAI", city:"Eastern Creek, Sydney", country:"Australia", countryCode:"AU", flag:"🇦🇺", region:"Asia Pacific", lat:-33.80, lng:150.84, status:"Announced", capacityMw:612, capacityLabel:"612 MW operational plan", capacityBasis:"Campus envelope", capacityDetail:"Planning documents describe 612 MW operational capacity; NEXTDC markets 550+ MW for the AI-ready campus.", detail:"A next-generation sovereign AI campus and planned large-scale GPU supercluster for Australia.", source:"https://www.nextdc.com/data-centres/sydney-data-centres/s7-sydney" },
  { id:"coreweave-denton", rank:24, name:"CoreWeave Denton", operator:"CoreWeave", city:"Denton, Texas", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:33.21, lng:-97.13, status:"Building", capacityMw:600, capacityLabel:"600 MW planned", capacityBasis:"Campus envelope", capacityDetail:"Full campus target tracked for 2027 delivery; initial commissioned halls will be smaller.", detail:"A GPU-focused neocloud campus designed for high-density training and inference clusters.", source:US_RANKING },
  { id:"tract-reno-2", rank:25, name:"Tract Reno NV2", operator:"Tract", city:"Reno, Nevada", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:39.52, lng:-119.82, status:"Announced", capacityMw:600, capacityLabel:"600 MW planned", capacityBasis:"Campus envelope", capacityDetail:"AI-ready master-plan figure; construction and utility delivery remain phased.", detail:"A second large Reno-area hyperscale campus built for future AI infrastructure tenants.", source:US_RANKING },
  { id:"project-mica", rank:26, name:"Project Mica", operator:"Google", city:"Kansas City region", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:39.10, lng:-94.58, status:"Building", capacityMw:538, capacityLabel:"538 MW planned", capacityBasis:"Planned", capacityDetail:"Reported project power plan for a new Google AI and cloud campus.", detail:"A large Google development intended to add substantial TPU and AI cloud capacity in the central US.", source:KNIGHT_FRANK },
  { id:"narvik", rank:27, name:"Narvik AI Campus", operator:"Nscale · Aker · Microsoft", city:"Narvik", country:"Norway", countryCode:"NO", flag:"🇳🇴", region:"Europe", lat:68.44, lng:17.43, status:"Building", capacityMw:520, capacityLabel:"520 MW expansion plan", capacityBasis:"Campus envelope", capacityDetail:"About 230 MW is reserved for the initial campus, with the wider Narvik plan seeking expansion toward 520 MW.", detail:"A hydropower-backed Arctic AI campus benefiting from low temperatures and strong industrial infrastructure.", source:"https://news.microsoft.com/source/emea/features/the-port-town-in-norway-emerging-as-an-ai-hub/" },
  { id:"ytl-johor", rank:28, name:"YTL Green AI Campus", operator:"YTL · NVIDIA", city:"Kulai, Johor", country:"Malaysia", countryCode:"MY", flag:"🇲🇾", region:"Asia Pacific", lat:1.66, lng:103.60, status:"Operational", capacityMw:500, capacityLabel:"500 MW campus plan", capacityBasis:"Campus envelope", capacityDetail:"Total green data-center park plan; the NVIDIA-powered AI cloud occupies a growing share of the site.", detail:"Southeast Asian sovereign AI infrastructure combining NVIDIA supercomputing and on-site solar generation.", source:"https://www.ytl.com/wp-content/uploads/ytles/sites/2/files/annual-report/YTLPI_AR2024.pdf" },
  { id:"humain-riyadh", rank:29, name:"HUMAIN AI Factory", operator:"HUMAIN · NVIDIA", city:"Riyadh", country:"Saudi Arabia", countryCode:"SA", flag:"🇸🇦", region:"Middle East", lat:24.71, lng:46.68, status:"Building", capacityMw:500, capacityLabel:"500 MW target", capacityBasis:"Planned", capacityDetail:"Program target announced for Saudi AI infrastructure; the first deployment begins with 18,000 GB300-class chips.", detail:"A national AI factory program designed to deliver large sovereign training and inference capacity.", source:"https://nvidianews.nvidia.com/news/saudi-arabia-ai-factories" },
  { id:"patagonia", rank:30, name:"Stargate Argentina", operator:"OpenAI · Sur Energy", city:"Patagonia", country:"Argentina", countryCode:"AR", flag:"🇦🇷", region:"Americas", lat:-39.80, lng:-68.90, status:"Announced", capacityMw:500, capacityLabel:"Up to 500 MW", capacityBasis:"Planned", capacityDetail:"Maximum proposed capacity; location, phasing, and final investment remain under development.", detail:"A proposed renewable-powered Stargate campus intended to anchor large-scale AI compute in Latin America.", source:"https://openai.com/index/stargate-argentina/" },
  { id:"stargate-wisconsin", rank:31, name:"Stargate Wisconsin", operator:"OpenAI · Oracle", city:"Port Washington, Wisconsin", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:43.39, lng:-87.88, status:"Building", capacityMw:500, capacityLabel:"~500 MW planned", capacityBasis:"Planned", capacityDetail:"Approximate campus envelope from the wider Stargate program; exact phase-level load is not publicly itemized.", detail:"One of OpenAI and Oracle's expanding Midwest AI campuses under the US Stargate program.", source:OPENAI_STARGATE },
  { id:"meta-el-paso", rank:32, name:"El Paso AI Campus", operator:"Meta", city:"El Paso, Texas", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:31.76, lng:-106.49, status:"Building", capacityMw:500, capacityLabel:"~500 MW tracked", capacityBasis:"Campus envelope", capacityDetail:"Planning estimate for the full AI-optimized campus; Meta has not published a final live IT-load figure.", detail:"A new Meta AI-optimized data center designed to scale with future accelerator demand.", source:META_INFRA },
  { id:"ellendale", rank:33, name:"Ellendale AI Campus", operator:"Applied Digital", city:"Ellendale, North Dakota", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:46.00, lng:-98.53, status:"Building", capacityMw:400, capacityLabel:"400 MW planned", capacityBasis:"Campus envelope", capacityDetail:"Combined campus target across phased high-performance computing buildings.", detail:"A purpose-built high-density campus serving AI and accelerated-computing customers.", source:"https://www.applieddigital.com/ellendale" },
  { id:"fairwater-wi", rank:34, name:"Fairwater Wisconsin", operator:"Microsoft", city:"Mount Pleasant, Wisconsin", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:42.72, lng:-87.90, status:"Operational", capacityMw:338, capacityLabel:"338 MW project capacity", capacityBasis:"Operational", capacityDetail:"Market-tracked campus power; Microsoft's first completed facility is operational with further expansion planned.", detail:"A liquid-cooled AI superfactory interconnecting hundreds of thousands of Blackwell accelerators.", source:"https://news.microsoft.com/source/2026/06/23/microsoft-completes-construction-on-first-datacenter-facility-in-mount-pleasant-wisconsin/" },
  { id:"syd3", rank:35, name:"AirTrunk SYD3", operator:"AirTrunk", city:"Western Sydney", country:"Australia", countryCode:"AU", flag:"🇦🇺", region:"Asia Pacific", lat:-33.82, lng:150.86, status:"Operational", capacityMw:320, capacityLabel:"320+ MW campus", capacityBasis:"Campus envelope", capacityDetail:"Total campus power designed for large hyperscale and high-density AI deployments.", detail:"One of Asia Pacific's largest hyperscale campuses, engineered for liquid-cooled AI expansion.", source:"https://airtrunk.com/data-centres/syd3/" },
  { id:"fairwater-atl", rank:36, name:"Fairwater Atlanta", operator:"Microsoft", city:"Atlanta, Georgia", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:33.75, lng:-84.39, status:"Operational", capacityMw:300, capacityLabel:"~300 MW tracked", capacityBasis:"Operational", capacityDetail:"Approximate project power from public infrastructure tracking; Microsoft does not publish a single final IT-load number.", detail:"Connected to Wisconsin through Microsoft's AI WAN to coordinate planet-scale training jobs.", source:"https://blogs.microsoft.com/blog/2025/11/12/infinite-scale-the-architecture-behind-the-azure-ai-superfactory/" },
  { id:"switch-citadel", rank:37, name:"Switch Citadel AI Campus", operator:"Switch", city:"Sparks, Nevada", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:39.53, lng:-119.74, status:"Building", capacityMw:300, capacityLabel:"300 MW expansion", capacityBasis:"Planned", capacityDetail:"Capacity shown for the newest AI-ready Citadel expansion tracked through 2026.", detail:"A high-security hyperscale campus adding liquid-cooled capacity for dense AI workloads.", source:US_RANKING },
  { id:"johor-bytedance", rank:38, name:"ByteDance Johor AI Campus", operator:"ByteDance", city:"Johor Bahru", country:"Malaysia", countryCode:"MY", flag:"🇲🇾", region:"Asia Pacific", lat:1.49, lng:103.74, status:"Building", capacityMw:250, capacityLabel:"~250 MW phase plan", capacityBasis:"Planned", capacityDetail:"Approximate multi-building capacity from public investment and planning disclosures.", detail:"A major Southeast Asian expansion supporting ByteDance AI, recommendation, and content infrastructure.", source:"https://www.mida.gov.my/mida-news/bytedance-to-invest-rm10-billion-in-malaysia-for-ai-hub/" },
  { id:"coreweave-lancaster", rank:39, name:"CoreWeave Lancaster", operator:"CoreWeave", city:"Lancaster, Pennsylvania", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:40.04, lng:-76.31, status:"Building", capacityMw:250, capacityLabel:"250 MW planned", capacityBasis:"Planned", capacityDetail:"Campus target for 2026 delivery, optimized for dense GPU clusters.", detail:"A GPU-native neocloud campus designed for frontier training, fine-tuning, and inference.", source:US_RANKING },
  { id:"meta-cheyenne", rank:40, name:"Cheyenne AI Campus", operator:"Meta", city:"Cheyenne, Wyoming", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:41.15, lng:-104.82, status:"Building", capacityMw:250, capacityLabel:"250 MW tracked", capacityBasis:"Planned", capacityDetail:"Public project tracking figure for the AI-optimized build; final IT load is not disclosed by Meta.", detail:"A new Meta campus using the company's more flexible AI-optimized data-center design.", source:META_INFRA },
  { id:"meta-dekalb", rank:41, name:"DeKalb AI Campus", operator:"Meta", city:"DeKalb, Illinois", country:"United States", countryCode:"US", flag:"🇺🇸", region:"Americas", lat:41.95, lng:-88.73, status:"Operational", capacityMw:250, capacityLabel:"250 MW campus", capacityBasis:"Operational", capacityDetail:"Tracked full-campus power across the existing and expanded AI-ready footprint.", detail:"A large Meta campus upgraded to serve the company's expanding recommendation and generative AI workloads.", source:META_INFRA },
  { id:"baidu-yangquan", rank:42, name:"Yangquan AI Computing Center", operator:"Baidu", city:"Yangquan, Shanxi", country:"China", countryCode:"CN", flag:"🇨🇳", region:"Asia Pacific", lat:37.86, lng:113.58, status:"Operational", capacityMw:230, capacityLabel:"~230 MW estimated", capacityBasis:"Campus envelope", capacityDetail:"Industry estimate for the expanded computing campus; Baidu reports compute scale more often than electrical IT load.", detail:"One of Baidu's principal intelligent-computing bases, supporting large-model training and cloud AI services.", source:"https://www.baidu.com/" },
  { id:"alibaba-zhangbei", rank:43, name:"Zhangbei AI Computing Base", operator:"Alibaba Cloud", city:"Zhangbei, Hebei", country:"China", countryCode:"CN", flag:"🇨🇳", region:"Asia Pacific", lat:41.15, lng:114.72, status:"Operational", capacityMw:200, capacityLabel:"~200 MW estimated", capacityBasis:"Operational", capacityDetail:"Industry estimate for the broader campus; Alibaba publishes compute capability more often than electrical IT load.", detail:"A major Alibaba cloud and AI computing base supporting large-scale model and recommendation workloads.", source:"https://www.alibabacloud.com/blog/alibaba-cloud-launches-its-third-data-center-in-zhangbei_594691" },
  { id:"khazna-abu-dhabi", rank:44, name:"Khazna AI Campus", operator:"Khazna · G42", city:"Abu Dhabi", country:"United Arab Emirates", countryCode:"AE", flag:"🇦🇪", region:"Middle East", lat:24.37, lng:54.52, status:"Operational", capacityMw:200, capacityLabel:"~200 MW portfolio campus", capacityBasis:"Campus envelope", capacityDetail:"Approximate combined campus envelope serving cloud and AI tenants; individual building load is lower.", detail:"A high-density regional campus supporting G42's sovereign AI and cloud infrastructure ecosystem.", source:"https://www.khazna.ae/" },
  { id:"google-hamina", rank:45, name:"Hamina AI & Cloud Campus", operator:"Google", city:"Hamina", country:"Finland", countryCode:"FI", flag:"🇫🇮", region:"Europe", lat:60.57, lng:27.19, status:"Operational", capacityMw:200, capacityLabel:"~200 MW estimated", capacityBasis:"Operational", capacityDetail:"Industry estimate across the expanded campus; Google does not publish facility-level IT load.", detail:"A seawater-cooled Google campus supporting European cloud services and TPU-based AI workloads.", source:"https://datacenters.google/locations/hamina/" },
  { id:"jhb1", rank:46, name:"AirTrunk JHB1", operator:"AirTrunk", city:"Johor Bahru", country:"Malaysia", countryCode:"MY", flag:"🇲🇾", region:"Asia Pacific", lat:1.56, lng:103.68, status:"Operational", capacityMw:150, capacityLabel:"150+ MW campus", capacityBasis:"Campus envelope", capacityDetail:"Total campus design capacity; the first 50+ MW phase is already commissioned.", detail:"An AI-ready liquid-cooled campus serving large technology customers in Southeast Asia.", source:"https://airtrunk.com/data-centres/jhb1/" },
  { id:"sakai", rank:47, name:"Sakai AI Data Center", operator:"SoftBank · Sharp", city:"Sakai, Osaka", country:"Japan", countryCode:"JP", flag:"🇯🇵", region:"Asia Pacific", lat:34.57, lng:135.48, status:"Building", capacityMw:150, capacityLabel:"150 MW target", capacityBasis:"Planned", capacityDetail:"Target after phased conversion of the former Sharp display manufacturing site.", detail:"A large industrial-site conversion designed for generative AI training and inference in Japan.", source:"https://www.softbank.jp/en/corp/news/press/sbkk/2024/20240607_01/" },
  { id:"loughton", rank:48, name:"Loughton AI Campus", operator:"Nscale · Microsoft", city:"Loughton", country:"United Kingdom", countryCode:"GB", flag:"🇬🇧", region:"Europe", lat:51.65, lng:0.06, status:"Building", capacityMw:90, capacityLabel:"~90 MW first build", capacityBasis:"Phase one", capacityDetail:"First-build estimate for the UK AI supercomputer campus; future expansion has not been fully disclosed.", detail:"A sovereign UK AI supercomputer campus designed for dense NVIDIA accelerator deployments.", source:"https://blogs.microsoft.com/blog/2025/09/18/inside-the-worlds-most-powerful-ai-datacenter/" },
  { id:"data4-paris", rank:49, name:"PAR AI Campus", operator:"DATA4", city:"Marcoussis, Paris", country:"France", countryCode:"FR", flag:"🇫🇷", region:"Europe", lat:48.64, lng:2.23, status:"Operational", capacityMw:80, capacityLabel:"~80 MW AI-ready", capacityBasis:"Campus envelope", capacityDetail:"Approximate AI-ready power across the expandable Paris campus; delivered capacity varies by building.", detail:"A major European campus adding liquid-cooled, high-density capacity for AI and HPC tenants.", source:"https://www.data4group.com/en/data-center-campus/paris/" },
  { id:"cassava-ai", rank:50, name:"Cassava AI Factory", operator:"Cassava Technologies · NVIDIA", city:"Johannesburg", country:"South Africa", countryCode:"ZA", flag:"🇿🇦", region:"Africa", lat:-26.20, lng:28.04, status:"Building", capacityMw:50, capacityLabel:"~50 MW first campus", capacityBasis:"Phase one", capacityDetail:"Estimated initial campus envelope; public announcements focus on GPU systems rather than exact electrical load.", detail:"Africa's first large NVIDIA-powered AI factory program, created to provide sovereign regional compute.", source:"https://www.cassavatechnologies.com/cassava-technologies-to-build-africas-first-ai-factory/" }
];

export const REGIONS = ["All regions", "Americas", "Europe", "Asia Pacific", "Middle East", "Africa"] as const;
