export type CompanyCampus = {
  rank: number;
  company: string;
  campus: string;
  capacityMw: number;
  capacity: string;
  location: string;
  country: string;
  status: string;
  statusTone: "operational" | "building" | "announced" | "mixed";
  basis: string;
  note: string;
  source: string;
  logo: string;
  sortingProxy?: boolean;
};

export const COMPANY_CAMPUSES: CompanyCampus[] = [
  { rank:1, company:"Meta", campus:"Hyperion", capacityMw:5000, capacity:"5 GW", location:"Richland Parish, Louisiana", country:"United States", status:"Building", statusTone:"building", basis:"Maximum campus envelope", note:"Designed to scale toward 5 GW. This is the maximum planned cluster scale, not today’s energized IT load.", source:"https://engineering.fb.com/2025/09/29/data-infrastructure/metas-infrastructure-evolution-and-the-advent-of-ai/", logo:"/company-logos/meta.png" },
  { rank:2, company:"Amazon Web Services", campus:"Project Rainier", capacityMw:2200, capacity:"2.2 GW", location:"Northern Indiana", country:"United States", status:"Operational + expanding", statusTone:"mixed", basis:"Multi-building campus", note:"The full campus figure includes the active Trainium AI cluster and continued expansion; AWS does not publish a separate live IT-load figure.", source:"https://preview.prod.sustainability.aboutamazon.com/stories/inside-amazons-approach-to-data-center-sustainability", logo:"/company-logos/aws.png" },
  { rank:3, company:"Microsoft", campus:"Pecos AI Campus", capacityMw:2000, capacity:"~2 GW", location:"Pecos, Texas", country:"United States", status:"Announced", statusTone:"announced", basis:"Planned capacity addition", note:"Microsoft says roughly 2 GW will be delivered over five to seven years, so the ranking uses the final planned scale.", source:"https://blogs.microsoft.com/blog/2026/06/22/powering-the-next-wave-of-ai-expanding-capacity-with-our-new-datacenter-in-pecos/", logo:"/company-logos/microsoft.png" },
  { rank:4, company:"Tract", campus:"Silver Springs Campus", capacityMw:1600, capacity:"Up to 1.6 GW", location:"Lyon County, Nevada", country:"United States", status:"Announced", statusTone:"announced", basis:"Maximum site support", note:"The site can support up to 1.6 GW. Its initial 700 MW remains subject to phased utility studies and tenant delivery.", source:"https://www.tract.com/news/tract-expands-its-greater-reno-portfolio-closing-on-1060-acres-in-silver-springs-nevada-following-successful-rezoning-and-development-agreement-with-lyon-county/", logo:"/company-logos/tract.png" },
  { rank:5, company:"DataVolt", campus:"Oxagon AI Factory", capacityMw:1500, capacity:"1.5 GW", location:"Oxagon, NEOM", country:"Saudi Arabia", status:"Development", statusTone:"building", basis:"Full project target", note:"The first investment phase is one part of a 1.5 GW renewable-powered AI factory planned to enter service from 2028.", source:"https://data-volt.com/media/breaking-news/datavolt-signs-agreement-with-neom-to-design-and-develop-the-regions-first-truly-sustainable-net-zero-ai-factory-campus-in-oxagon/", logo:"/company-logos/datavolt.png" },
  { rank:6, company:"Vantage Data Centers", campus:"Frontier", capacityMw:1400, capacity:"1.4 GW", location:"Shackelford County, Texas", country:"United States", status:"Announced", statusTone:"announced", basis:"Critical IT load", note:"The full-build plan spans ten data centers engineered for dense, liquid-cooled AI deployments.", source:"https://vantage-dc.com/news/vantage-data-centers-unveils-plans-for-frontier-a-25b-mega-campus-in-texas-to-meet-unprecedented-ai-demand/", logo:"/company-logos/vantage.png" },
  { rank:7, company:"Nscale", campus:"Monarch AI Campus", capacityMw:1350, capacity:"Up to 1.35 GW", location:"Mason County, West Virginia", country:"United States", status:"Announced", statusTone:"announced", basis:"Compute letter of intent", note:"The up-to figure comes from a Microsoft Vera Rubin compute letter of intent, not currently energized capacity.", source:"https://www.nscale.com/press-releases/nscale-west-virginia-ai-factory", logo:"/company-logos/nscale.png" },
  { rank:8, company:"OpenAI · G42", campus:"Stargate UAE", capacityMw:1000, capacity:"1 GW", location:"Abu Dhabi", country:"United Arab Emirates", status:"Building", statusTone:"building", basis:"Dedicated Stargate cluster", note:"The dedicated cluster starts with a 200 MW phase inside the wider 5 GW UAE–US AI campus.", source:"https://openai.com/index/introducing-stargate-uae/", logo:"/company-logos/openai-g42.png" },
  { rank:9, company:"Google · AdaniConneX", campus:"Visakhapatnam AI Hub", capacityMw:1000, capacity:"Gigawatt-scale*", location:"Andhra Pradesh", country:"India", status:"Announced", statusTone:"announced", basis:"Official scale description", note:"Google says “gigawatt-scale” but gives no exact MW. A 1,000 MW proxy is used only to place the project in this ranking.", source:"https://blog.google/intl/en-in/company-news/our-first-ai-hub-in-india-powered-by-a-15-billion-investment/", logo:"/company-logos/google-adani.png", sortingProxy:true },
  { rank:10, company:"Reliance Industries", campus:"Jamnagar AI Campus", capacityMw:1000, capacity:"Gigawatt-scale*", location:"Jamnagar, Gujarat", country:"India", status:"Building", statusTone:"building", basis:"Long-range program direction", note:"Reliance describes the wider campus program as gigawatt-scale. The separately contracted first Meta facility is 168 MW.", source:"https://www.ril.com/news-media/events/reliance-at-the-forefront", logo:"/company-logos/reliance.svg", sortingProxy:true },
  { rank:11, company:"DATA4", campus:"Escaudain AI Campus", capacityMw:700, capacity:"700 MW", location:"Hauts-de-France", country:"France", status:"Announced", statusTone:"announced", basis:"Full-campus electrical capacity", note:"A future cloud and AI campus whose published figure represents the completed site rather than an operating hall.", source:"https://www.data4group.com/en/news-data4/in-northern-france-data4-launches-its-largest-data-center-campus-to-support-europes-ai-growth/", logo:"/company-logos/data4.png" },
  { rank:12, company:"NEXTDC", campus:"S7 Sydney", capacityMw:550, capacity:"550+ MW", location:"Eastern Creek, Sydney", country:"Australia", status:"Planned", statusTone:"announced", basis:"Planned IT capacity", note:"NEXTDC markets S7 as a 550+ MW AI-ready campus; delivery remains subject to approvals and phased construction.", source:"https://www.nextdc.com/data-centres/sydney-data-centres/s7-sydney", logo:"/company-logos/nextdc.png" },
  { rank:13, company:"Aligned Data Centers", campus:"Project Caprock", capacityMw:540, capacity:"540 MW", location:"Hale County, Texas", country:"United States", status:"Building", statusTone:"building", basis:"Six-facility campus", note:"Published campus capacity across six cloud and AI-ready facilities, not one data hall.", source:"https://aligneddc.com/press-release/aligned-breaks-ground-on-project-caprock/", logo:"/company-logos/aligned.png" },
  { rank:14, company:"YTL Power", campus:"YTL Green Data Center Park", capacityMw:500, capacity:"500 MW", location:"Kulai, Johor", country:"Malaysia", status:"Operational + building", statusTone:"mixed", basis:"Entire park capacity", note:"The operational NVIDIA AI deployment occupies only part of the wider renewable-powered data center park.", source:"https://www.ytl.com/beyond70/museum/era-three/", logo:"/company-logos/ytl.png" },
  { rank:15, company:"atNorth", campus:"DEN02 Varde", capacityMw:500, capacity:"500 MW", location:"Varde", country:"Denmark", status:"Planned", statusTone:"announced", basis:"Full campus power", note:"The 500 MW campus begins with an initial 250 MW development phase.", source:"https://www.atnorth.com/nordic-data-centers/denmark-data-centers/varde-mega-site/", logo:"/company-logos/atnorth.png" },
  { rank:16, company:"Khazna · Eni", campus:"Ferrera Erbognone AI Campus", capacityMw:500, capacity:"500 MW", location:"Lombardy", country:"Italy", status:"Announced", statusTone:"announced", basis:"Planned IT capacity", note:"The figure is covered by heads of terms; final partnership terms and phase delivery still matter.", source:"https://khaznadatacenters.com/press-release/khazna-data-centers-and-eni-partner-to-develop-500-mw-ai-data-center-campus-near-milan/", logo:"/company-logos/khazna.png" },
  { rank:17, company:"DataBank", campus:"Red Oak Campus", capacityMw:480, capacity:"480 MW", location:"Red Oak, Texas", country:"United States", status:"Building", statusTone:"building", basis:"Full-build critical IT", note:"The final campus is planned for 480 MW; its first construction phase accounts for 240 MW.", source:"https://www.databank.com/resources/blogs/building-the-future-inside-databanks-red-oak-campus-construction/", logo:"/company-logos/databank.png" },
  { rank:18, company:"Applied Digital", campus:"Polaris Forge 1", capacityMw:400, capacity:"400 MW", location:"Ellendale, North Dakota", country:"United States", status:"Operational + building", statusTone:"mixed", basis:"Critical IT load", note:"The company filing reports 100 MW energized with the remaining campus capacity under construction in 2026.", source:"https://ir.applieddigital.com/sec-filings/all-sec-filings/content/0001493152-26-005788/form8-k.htm", logo:"/company-logos/applied-digital.png" },
  { rank:19, company:"ST Telemedia GDC", campus:"STT Jakarta Campus", capacityMw:360, capacity:"360+ MW", location:"Cikarang, Greater Jakarta", country:"Indonesia", status:"Operational + building", statusTone:"mixed", basis:"Multi-building pipeline", note:"The long-range IT-capacity pipeline spans several buildings and delivery phases rather than one live hall.", source:"https://www.sttelemediagdc.com/id-en/newsroom/stt-gdc-accelerates-jakarta-campus-expansion-power-indonesia-ai-and-digital-ambitions", logo:"/company-logos/stt-gdc.png" },
  { rank:20, company:"Compass Datacenters", campus:"DFW Red Oak", capacityMw:360, capacity:"360 MW", location:"Red Oak, Texas", country:"United States", status:"Building", statusTone:"building", basis:"Campus development capacity", note:"The operator publishes campus scale; tenant-specific AI load remains undisclosed.", source:"https://www.compassdatacenters.com/data-center-markets/", logo:"/company-logos/compass.png" },
  { rank:21, company:"AirTrunk", campus:"SYD3", capacityMw:320, capacity:"320+ MW", location:"Western Sydney", country:"Australia", status:"Operational", statusTone:"operational", basis:"Whole campus capacity", note:"The live hyperscale campus supports high-density AI deployments but is not used exclusively for AI.", source:"https://airtrunk.com/data-centres/syd3/", logo:"/company-logos/airtrunk.png" },
  { rank:22, company:"CoreWeave", campus:"Lancaster AI Data Center", capacityMw:300, capacity:"Up to 300 MW", location:"Lancaster, Pennsylvania", country:"United States", status:"Building", statusTone:"building", basis:"Expansion potential", note:"The initial committed facility is 100 MW, with expansion potential taking the site toward 300 MW.", source:"https://investors.coreweave.com/news/news-details/2025/CoreWeave-Announces-Multi-Billion-Dollar-Commitment-to-AI-Infrastructure-in-Pennsylvania/default.aspx", logo:"/company-logos/coreweave.png" },
  { rank:23, company:"Prime Data Centers", campus:"Chicago ORD01 Campus", capacityMw:270, capacity:"270 MW", location:"Elk Grove Village, Illinois", country:"United States", status:"Operational + building", statusTone:"mixed", basis:"Three-building critical IT", note:"The published total covers three AI-ready buildings at different delivery stages.", source:"https://primedatacenters.com/locations/chicago/", logo:"/company-logos/prime.png" },
  { rank:24, company:"NTT DATA", campus:"Phoenix Campus", capacityMw:240, capacity:"240 MW", location:"Mesa, Arizona", country:"United States", status:"Operational + building", statusTone:"mixed", basis:"Full-campus critical IT", note:"The figure covers the entire expanding campus; each individual operational building is smaller.", source:"https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/americas/phoenix-data-centers", logo:"/company-logos/ntt-data.png" },
  { rank:25, company:"STACK Infrastructure", campus:"Johor Bahru Campus", capacityMw:220, capacity:"220 MW", location:"Iskandar Puteri, Johor", country:"Malaysia", status:"Building", statusTone:"building", basis:"Two-building campus", note:"A hyperscale campus designed for cloud and AI/ML workloads, with capacity delivered in phases.", source:"https://www.stackinfra.com/about/news-press/press-releases/stack-infrastructure-announces-220mw-campus-in-malaysia/", logo:"/company-logos/stack.png" },
  { rank:26, company:"EdgeConneX", campus:"Greater Osaka Campus", capacityMw:200, capacity:"200 MW", location:"Osaka", country:"Japan", status:"Building", statusTone:"building", basis:"Campus electrical capacity", note:"The AI-ready campus is under construction, with its first phase expected to enter service in 2028.", source:"https://www.edgeconnex.com/news/press-releases/edgeconnex-commences-construction-of-200mw-ai-ready-hyperscale-campus-in-greater-osaka/", logo:"/company-logos/edgeconnex.png" },
  { rank:27, company:"DC BLOX", campus:"Atlanta West", capacityMw:200, capacity:"200 MW", location:"Douglasville, Georgia", country:"United States", status:"Building", statusTone:"building", basis:"Planned critical load", note:"A purpose-built AI-ready hyperscale campus whose published capacity represents full development.", source:"https://www.dcblox.com/hyperscale-data-center/", logo:"/company-logos/dcblox.png" },
  { rank:28, company:"Digital Realty", campus:"Dugny Digital Hub", capacityMw:176, capacity:"176 MW", location:"Dugny, Paris", country:"France", status:"Building", statusTone:"building", basis:"Three data centers", note:"The total IT capacity spans three AI-ready facilities; the first delivery is planned for 2027.", source:"https://www.digitalrealty.com/about/projects/dugny-digital-hub", logo:"/company-logos/digital-realty.png" },
  { rank:29, company:"CyrusOne", campus:"LON6", capacityMw:90, capacity:"90 MW", location:"Iver Heath, Buckinghamshire", country:"United Kingdom", status:"Announced", statusTone:"announced", basis:"Planned IT load", note:"A planned London-region facility; the figure is not current operating load.", source:"https://www.cyrusone.com/resources/press-releases/cyrusone-plans-pioneering-new-london-facility-with-sustainability-at-its-core", logo:"/company-logos/cyrusone.png" },
  { rank:30, company:"Pure DC", campus:"Amsterdam Westpoort AMS01", capacityMw:78, capacity:"78 MW", location:"Amsterdam", country:"Netherlands", status:"Building", statusTone:"building", basis:"High-density campus", note:"The substation is live while the data halls remain under phased construction.", source:"https://puredc.com/amsterdam", logo:"/company-logos/pure-dc.png" },
];
