import * as THREE from 'https://esm.sh/three@0.178.0';
import './styles.css';

const centers = [
  {name:'Stargate Abilene', company:'OpenAI / Oracle / SoftBank', city:'Abilene, TX', lat:32.4487, lon:-99.7331, mw:1200, status:'Under construction', chips:'NVIDIA GB200/AI clusters', note:'Flagship Stargate campus; public plans describe multi-GW AI capacity.'},
  {name:'xAI Colossus', company:'xAI', city:'Memphis, TN', lat:35.1495, lon:-90.0490, mw:300, status:'Operating / expanding', chips:'100k+ GPU supercluster', note:'One of the largest known dedicated AI training supercomputers.'},
  {name:'Microsoft Fairwater', company:'Microsoft', city:'Mount Pleasant, WI', lat:42.7261, lon:-87.7829, mw:500, status:'Operating / expanding', chips:'Azure AI supercomputer', note:'Microsoft describes Fairwater as a massive AI datacenter region.'},
  {name:'Meta Hyperion', company:'Meta', city:'Richland Parish, LA', lat:32.3876, lon:-91.7539, mw:5000, status:'Planned / phased build', chips:'AI training infrastructure', note:'Public reporting places this among the largest announced AI campuses.'},
  {name:'Meta Prometheus', company:'Meta', city:'New Albany, OH', lat:40.0812, lon:-82.8088, mw:1000, status:'Planned / expanding', chips:'AI accelerators', note:'A major Ohio AI campus associated with Meta infrastructure expansion.'},
  {name:'Homer City AI Campus', company:'Homer City / Kiewit / energy partners', city:'Homer City, PA', lat:40.5434, lon:-79.1620, mw:4500, status:'Under construction', chips:'Hyperscale AI-ready', note:'Reuse of a former power-generation site for a multi-GW AI campus.'},
  {name:'CoreWeave Lancaster', company:'CoreWeave', city:'Lancaster, TX', lat:32.5921, lon:-96.7561, mw:450, status:'Operating / expanding', chips:'NVIDIA cloud GPUs', note:'Neocloud AI infrastructure in the fast-growing Dallas-Fort Worth market.'},
  {name:'Oracle Cloud AI Region', company:'Oracle', city:'Ashburn, VA', lat:39.0438, lon:-77.4874, mw:300, status:'Operating', chips:'OCI GPU clusters', note:'Northern Virginia remains the densest U.S. cloud and AI data-center hub.'},
  {name:'AWS Project Rainier', company:'Amazon / Anthropic', city:'New Carlisle, IN', lat:41.7003, lon:-86.5095, mw:600, status:'Building / expanding', chips:'Trainium AI chips', note:'Amazon is building large AI infrastructure for frontier model workloads.'},
  {name:'Google AI Cloud Campus', company:'Google', city:'Council Bluffs, IA', lat:41.2619, lon:-95.8608, mw:300, status:'Operating / expanding', chips:'TPU/GPU clusters', note:'A long-running Google cloud campus used for modern AI services.'},
  {name:'Crusoe AI Campus', company:'Crusoe', city:'Abilene, TX', lat:32.407, lon:-99.83, mw:200, status:'Under construction', chips:'GPU cloud', note:'AI infrastructure buildout adjacent to the wider Abilene AI cluster.'},
  {name:'Tesla Cortex', company:'Tesla', city:'Austin, TX', lat:30.2672, lon:-97.7431, mw:130, status:'Operating / expanding', chips:'Dojo + NVIDIA GPUs', note:'AI compute for autonomy and robotics workloads.'}
];
let selected = 0;
const app = document.getElementById('root');
app.innerHTML = `<main><section class="hero"><nav><b>◈ AI Data Center Atlas</b><a href="https://github.com/">GitHub</a></nav><div class="copy"><p class="eyebrow">Major United States AI infrastructure</p><h1>A cinematic Three.js map of America's frontier AI compute campuses.</h1><p>Explore large public AI datacenter projects from hyperscalers, neoclouds, and dedicated model-training campuses. Motion, glow, depth, and scale emphasize compute intensity—not exact real-estate boundaries.</p><div class="stats"><span>⚡ ~${(centers.reduce((a,c)=>a+c.mw,0)/1000).toFixed(1)} GW tracked</span><span>▦ ${centers.length} major sites</span><span>⌖ AI-focused only</span></div></div><div class="panel"><canvas id="map"></canvas><div class="hint">Scroll to zoom. Drag to orbit. Click glowing markers.</div></div></section><section class="details"><article class="card feature" id="feature"></article><div class="grid" id="grid"></div></section><footer>Curated snapshot of major publicly reported AI-focused U.S. sites. Verify capacity and status before operational decisions.</footer></main>`;
function renderDetails(){const d=centers[selected];document.getElementById('feature').innerHTML=`<span>${d.status}</span><h2>${d.name}</h2><h3>${d.company} · ${d.city}</h3><p>${d.note}</p><dl><div><dt>Estimated scale</dt><dd>${d.mw.toLocaleString()} MW</dd></div><div><dt>Compute</dt><dd>${d.chips}</dd></div><div><dt>Coordinates</dt><dd>${d.lat.toFixed(3)}, ${d.lon.toFixed(3)}</dd></div></dl>`;document.getElementById('grid').innerHTML=centers.map((c,i)=>`<button class="${i===selected?'active':''}" data-i="${i}"><strong>${c.name}</strong><small>${c.company}</small><em>${c.city} · ${c.mw} MW</em></button>`).join('');document.querySelectorAll('.grid button').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;renderDetails();updateMarkerColors();});}
renderDetails();
const canvas=document.getElementById('map'), scene=new THREE.Scene(); scene.background=new THREE.Color('#050816'); scene.fog=new THREE.Fog('#050816',8,18); const camera=new THREE.PerspectiveCamera(46,1,.1,100); camera.position.set(0,5.2,7.8); const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); scene.add(new THREE.AmbientLight(0x8aa4ff,1)); const sun=new THREE.DirectionalLight(0xffffff,2); sun.position.set(4,6,3); scene.add(sun);
const group=new THREE.Group(); scene.add(group); const plane=new THREE.Mesh(new THREE.PlaneGeometry(11,6,80,44),new THREE.MeshStandardMaterial({color:0x0f172a,metalness:.25,roughness:.55,wireframe:true})); plane.rotation.x=-Math.PI/2; group.add(plane); const base=new THREE.Mesh(new THREE.PlaneGeometry(11.2,6.2),new THREE.MeshStandardMaterial({color:0x07111f,metalness:.4,roughness:.4})); base.rotation.x=-Math.PI/2; base.position.y=-.03; group.add(base);
function project(lat, lon){return [(lon+125)/58*10-5, -(lat-24)/26*5+2.5];} const markers=[]; centers.forEach((d,i)=>{const [x,z]=project(d.lat,d.lon), s=.18+Math.log10(d.mw)/10; const marker=new THREE.Mesh(new THREE.OctahedronGeometry(s,0),new THREE.MeshStandardMaterial({color:0xa78bfa,emissive:0x7c3aed,emissiveIntensity:1.2})); marker.position.set(x,.35,z); marker.scale.y=2.2; marker.userData.index=i; group.add(marker); const light=new THREE.PointLight(0x7dd3fc,5,2.2); light.position.set(x,.45,z); group.add(light); markers.push({marker,light,d});});
function updateMarkerColors(){markers.forEach((m,i)=>{m.marker.material.color.set(i===selected?'#67e8f9':'#a78bfa');m.marker.material.emissive.set(i===selected?'#22d3ee':'#7c3aed');m.light.intensity=i===selected?18:5;});} updateMarkerColors();
const ray=new THREE.Raycaster(), mouse=new THREE.Vector2(); canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(); mouse.x=((e.clientX-r.left)/r.width)*2-1; mouse.y=-((e.clientY-r.top)/r.height)*2+1; ray.setFromCamera(mouse,camera); const hit=ray.intersectObjects(markers.map(m=>m.marker))[0]; if(hit){selected=hit.object.userData.index;renderDetails();updateMarkerColors();}}); let targetRot={x:-.75,z:0}, zoom=7.8; canvas.addEventListener('pointermove',e=>{if(e.buttons){targetRot.z+=(e.movementX||0)*.004; targetRot.x+=(e.movementY||0)*.004;}}); canvas.addEventListener('wheel',e=>{e.preventDefault(); zoom=Math.max(4.8,Math.min(11,zoom+e.deltaY*.004));},{passive:false});
function resize(){const r=canvas.parentElement.getBoundingClientRect(); renderer.setSize(r.width,r.height,false); camera.aspect=r.width/r.height; camera.updateProjectionMatrix();} addEventListener('resize',resize); resize(); const clock=new THREE.Clock(); function animate(){const t=clock.getElapsedTime(); group.rotation.x=targetRot.x+Math.sin(t*.22)*.025; group.rotation.z=targetRot.z+Math.sin(t*.16)*.018; camera.position.z+=(zoom-camera.position.z)*.05; markers.forEach((m,i)=>{m.marker.position.y=.32+Math.sin(t*2+i)*.08; m.marker.rotation.y+=.01; m.light.position.y=m.marker.position.y+.12;}); renderer.render(scene,camera); requestAnimationFrame(animate);} animate();
